### ISSUE TITLE
minion/master file.recurse needs to stop using clean: True

### ISSUE THREAD

**Issue by iggy** [saltstack-formulas/salt-formula#104]
The salt [code](https://github.com/saltstack/salt/blob/26acc5c1d476284174ba988439a2cc08ce66dc61/salt/utils/schedule.py#L302) (and myself) put files in /etc/salt/{master,minion}.d

The "clean: True" is killing all that. It probably shouldn't do that.

```
salt-minion:
  file.recurse:
    - name: {{ salt.get('config-path', '/etc/salt') }}/minion.d
    - template: jinja
    - source: salt://salt/files/minion.d
    - clean: True
    - context:
        standalone: False
```
