### ISSUE TITLE
[salt-master-2015.8.0-2.el6] salt.minion ends up with values from salt.master's grains in config file, cannot start

### ISSUE THREAD

**Issue by blast-hardcheese** [saltstack-formulas/salt-formula#178]
# Configuration:
This is surprisingly easy to reproduce:

### `/srv/salt/top.sls`:
```
base:
  '*':
    - salt.minion

  'G@roles:master':
    - salt.master
```

### `/srv/pillar/master.sls`:
```
salt:
  master:
    fileserver_backend:
      - roots
      - git

    file_roots:
      base:
        - /srv/salt

    pillar_roots:
      base:
        - /srv/pillar

    gitfs_provider: pygit2

    gitfs_remotes:
      - git://github.com/saltstack-formulas/salt-formula
```

### `/srv/pillar/minion.sls`:
```
salt:
  minion:
    - master: 'salt'
```

`/srv/pillar/top.sls`:
```
base:
  '*':
    - minion

  'G@roles:master':
    - master
```

# Results:

Given those values, I end up with the following in `/etc/salt/minion.d/f_defaults.conf`:

```
[root@pluto ~]# grep -v '^#' /etc/salt/minion.d/f_defaults.conf | uniq

master:
  - fileserver_backend
  - gitfs_remotes
  - pillar_roots
  - file_roots
  - gitfs_provider
  

[root@pluto ~]#
```
