### ISSUE TITLE
Existing salt.formulas configurations broken by recent pull request

### ISSUE THREAD

**Issue by xenophonf** [saltstack-formulas/salt-formula#201]
Pull request #200 changed how this formula manage formulas on Salt masters in a backwards-incompatible way.  This causes the `salt.formulas` SLS to fail on masters that use the old-style format of the `salt_formulas:list` Pillar key, which mapped environments to lists of formulas to be cloned, with errors similar to the following:

```
local:
    Data failed to compile:
----------
    Rendering SLS 'development:salt.formulas' failed: Jinja variable 'list object' has no attribute 'items'
```

I like the idea of overriding the `baseurl` parameter on a per-formula basis (previously, it could only be overridden on a per-environment basis).  I would propose that this formula adopt a [`gitfs_remotes`-style](https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#per-remote-configuration-parameters) override mechanism.  For example:

```yaml
salt_formulas:
  git_opts:
    default:
      baseurl: https://github.com/saltstack-formulas
  list:
    base:
      - openssh-formula
      - salt-formula
      - users-formula
    dev:
      - openssh-formula:
          baseurl: git@github.com:irtnog
      - salt-formula:
          baseurl: git@github.com:irtnog
      - users-formula:
          baseurl: git@github.com:irtnog
```

This would preserve backwards compatibility while still affording end users the ability to override the formula's base URL on a case-by-case basis.  In the meantime I think that #200 should be reverted---and the original behavior of the salt.formulas SLS restored.

**Comment by xenophonf** [comment]
In the meantime I think that #200 should be reverted---and the original behavior of the `salt.formulas` SLS restored.

**Comment by mercsniper** [comment]
Gents, 

I am seeing the following when the file is rendering:

```

/srv/formulas/{'salt-formula-jenkins': {'baseurl': 'https://github.com/salt-formulas'}}:
  git.latest:
    - name: https://github.com/saltstack-formulas/{'salt-formula-jenkins': {'baseurl': 'https://github.com/salt-formulas'}}.git
    - target: /srv/formulas/{'salt-formula-jenkins': {'baseurl': 'https://github.com/salt-formulas'}}
    - require:
      - file: /srv/formulas
    - unless: test -e /srv/formulas/{'salt-formula-jenkins': {'baseurl': 'https://github.com/salt-formulas'}}
```

Are the loops processing the overrides properly instead of passing the entire dictionary?
