### ISSUE TITLE
Prevent erroneous remote tracking branch modification by `salt.formulas`

### ISSUE THREAD

**Issue by myii** [saltstack-formulas/salt-formula#238]
##### Starting point

```
salt_formulas:
  git_opts:
    default:
      baseurl: git@github.com:myii
```

```
$ git remote -v
origin  git@github.com:myii/nginx-formula.git (fetch)
origin  git@github.com:myii/nginx-formula.git (push)
upstream        git@github.com:saltstack-formulas/nginx-formula.git (fetch)
upstream        git@github.com:saltstack-formulas/nginx-formula.git (push)
```

```
$ git branch -vv
  master   5fc7685 [origin/master] Merge pull request #103 from percipient/fix-nginx-kill
* upstream 5fc7685 [upstream/master: behind 28] Merge pull request #103 from percipient/fix-nginx-kill
```
- Note that the `upstream` branch is currently checked out, which tracks `upstream/master`
##### Issue after running `salt.formulas`

```
# salt 'my_minion' state.sls salt.formulas

...

          ID: /srv/Salt/formulas/nginx-formula
    Function: git.latest
        Name: git@github.com:myii/nginx-formula.git
      Result: True
     Comment: Repository /srv/Salt/formulas/nginx-formula is up-to-date

              Changes made: Tracking branch was updated to origin/master
     Started: 17:30:58.774605
    Duration: 3006.362 ms
     Changes:
```

```
$ git branch -vv
  master   5fc7685 [origin/master] Merge pull request #103 from percipient/fix-nginx-kill
* upstream 5fc7685 [origin/master] Merge pull request #103 from percipient/fix-nginx-kill
```
- Unwanted remote tracking branch modification from `upstream/master` to `origin/master`
#### Suggested solution

Already understood that this can be avoided by adding the `branch` option to the pillar:

```
salt_formulas:
  git_opts:
    default:
      options:
        branch: master
```

However, suggesting to add a conditional block to the `git.latest` state in `formulas.sls`, setting the `branch: master` option by default, if no specific value set in the pillar:

```
{{ gitdir }}:
  git.latest:
    - name: {{ baseurl }}/{{ entry }}.git
    - target: {{ gitdir }}
    {%- if 'branch' not in options.items() %}
    - branch: master
    {%- endif %}
    {%- for key, value in options.items() %}
    - {{ key }}: {{ value }}
    {%- endfor %}
    ...
```

This then avoids the problem outlined above:

```
# salt 'my_minion' state.sls salt.formulas

...

          ID: /srv/Salt/formulas/nginx-formula
    Function: git.latest
        Name: git@github.com:myii/nginx-formula.git
      Result: True
     Comment: Repository /srv/Salt/formulas/nginx-formula is up-to-date

              Changes made: 'master' was checked out
     Started: 17:37:55.763145
    Duration: 3842.103 ms
     Changes:
```
#### Notes

Another side effect of this issue is that the remote tracking branch is set whichever branch is currently checked out, such as a local `dev` branch:

```
* dev      5fc7685 Merge pull request #103 from percipient/fix-nginx-kill
```

Unfortunately becomes:

```
* dev      5fc7685 [origin/master] Merge pull request #103 from percipient/fix-nginx-kill
```

Happy to submit a PR if approved.
