### ISSUE TITLE
Adding non-default config options to master.d/minion.d config

### ISSUE THREAD

**Issue by mrichar1** [saltstack-formulas/salt-formula#246]
I can't see a way to add a config option to the f_defaults.conf files in either master.d/minion.d that aren't already specified in the template.

For example, the kerberos module expects some custom values in the minion config: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.kerberos.html

The following will not be added to the config file from pillar data:

```
salt:
  minion:
    auth_keytab: /root/auth.keytab
    auth_principal: kadmin/admin
```
