### ISSUE TITLE
pkgrepo state name conflicts with os_family_map

### ISSUE THREAD

**Issue by haraldrudell** [saltstack-formulas/salt-formula#272]
CAUSE
Because:
- the pkgrepo state ie. **salt://salt/pkgrepo/init.sls** has the same name as pkgrepo found in map.jinja variable **os_family_map**

then:
- trying to use the pkgrepo state overwrites the deb line used.

FIX
Rename the pkgrepo state to a non-conflicting name like **saltrepo**

SYMPTOM
```
          ID: saltstack-pkgrepo
    Function: pkgrepo.managed
        Name: None
      Result: False
     Comment: Failed to configure repo 'None': Error: HTTP 404: Not Fo
und reading https://repo.saltstack.com/apt/ubuntu/16.10/amd64/latest/S
ALTSTACK-GPG-KEY.pub
     Started: 06:48:03.712360
    Duration: 1170.031 ms
     Changes:   
```
