### ISSUE TITLE
Example of ext_pillar?

### ISSUE THREAD

**Issue by devinnasar** [saltstack-formulas/salt-formula#309]
Hello,

I'd like to set up my master to pull from external pillars but I don't know how to write that up in the pillar file. Could you please provide an example? Thanks!

**Comment by javierbertoli** [comment]
Hi @devinnasar,

You should add something like this to your pillar:
```yaml
salt:
  master:
    ext_pillar:
      - example_a: some argument
      - example_b:
        - argumentA
        - argumentB
```
You can check the general syntax for the `ext_pillar` parameter [here](https://docs.saltstack.com/en/latest/topics/development/external_pillars.html). The arguments will depend on which external pillar do you plan to use.

As an example, [pillarstack](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.stack.html) entry will look like this:
```yaml
salt:
  master:
    ext_pillar:
      - stack: /var/lib/pillarstack/stack.cfg
```

[These are the lines in the formula](https://github.com/saltstack-formulas/salt-formula/blob/master/salt/files/master.d/f_defaults.conf#L1153-L1186) that manage this parameter in the master configuration.

Hope this helps
