### ISSUE TITLE
Default pkgrepo and key_url fail on Ubuntu *.10 versions

### ISSUE THREAD

**Issue by alexander-bauer** [saltstack-formulas/salt-formula#310]
Using `salt.pkgrepo` on Ubuntu 16.10 (and other `*.10` versions, I would guess, by looking at the available Ubuntu repositories), the `saltstack-pkgrepo` state fails because the package repository URL that is created does not exist. This is because the repository URL is created using `grains['os']` and `grains['osrelease']`, for which a repository does not actually exist.

I was able to work around this by specifying the repository for Ubuntu 16.04 in the pillars. I don't know if there is a good way to work around this in general, because it might be preferable to fail than to use an unexpectedly older version, but a note in the documentation would be nice.

Here is my workaround snippet.
```yaml
# pillars/salt.sls
salt:
  # ...
  {% if grains['os'] == 'Ubuntu' and grains['osrelease'] == '16.10' %}
  key_url: 'http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub'
  pkgrepo: 'deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main'
  {% endif %}
```
