### ISSUE TITLE
{master,minion}.conf template custom settings

### ISSUE THREAD

**Issue by llua** [saltstack-formulas/salt-formula#340]
I want to pose the question: should keys not handled by the templates be added to an `custom_settings`-like hash in pillar instead of their current level `{ 'salt': { 'minion': { 'key': 'value' } } }`?

I ran into the bug https://github.com/saltstack/salt/issues/44378 since i was setting `schedule` prior to the template handling it, like so:
```
salt:
  minion:
    schedule:
      foo: { ... }
```
Once `schedule` was added to the template, the formula was setting schedule to an null value since my pillar wasn't formatted the way that the template now expected it to be.

Had the custom settings that the template allows setting, required placing them like so
```
salt:
  minion:
    custom_settings:
      schedule:
        ...
```

When i updated the formula, it would've still correctly generated my minion config, not changing `schedule`.

I understand that changing this in the templates will effectively do what i would like to avoid for people who currently rely on how it works now, but i think overall its a good idea.

**Comment by joe-bowman** [comment]
I've just come across this very same error trying to set a schedule, in that the templated form (as used for minion.d/f_defaults.conf) doesn't accept lists (the `args` param is a list); so my config
```
salt:
  minion:
    schedule:
      repo_update:
        function: git.pull
        seconds: 300
        maxrunning: 1
        args:
          - /srv/repo
        kwargs:
          identity: /root/.ssh/github
```
which works fine when copied directly into the f_default.conf file; _and_ works when set for the master (as schedules are _not_ formatted under `salt.master` state) fails to run.

For values that are to be output as yaml, arguably should not be forced through some template that doesn't fit all cases; there needs to be some trust in the user to read the docs rather than trying to hand-hold.

Workaround for now is to declare as a JSON string; but this is daft considering both pillar and the config we are generating can be yaml.
