### ISSUE TITLE
Base URL for specifing a non-default URL broken

### ISSUE THREAD

**Issue by mercsniper** [saltstack-formulas/salt-formula#342]
As written, and mentioned in #201 and #202 Formulas in salt-formulas.sls can be overridden by adding a baseurl override. When you do it in yaml though, I found that it is inserting the entire dictionary into the parameters of the state. Here is a debug output:

```

/srv/formulas/{'salt-formula-jenkins': {'baseurl': 'https://github.com/salt-formulas'}}:
  git.latest:
    - name: https://github.com/saltstack-formulas/{'salt-formula-jenkins': {'baseurl': 'https://github.com/salt-formulas'}}.git
    - target: /srv/formulas/{'salt-formula-jenkins': {'baseurl': 'https://github.com/salt-formulas'}}
    - require:
      - file: /srv/formulas
    - unless: test -e /srv/formulas/{'salt-formula-jenkins': {'baseurl': 'https://github.com/salt-formulas'}}

```
