### ISSUE TITLE
publisher_acl and underlying keys

### ISSUE THREAD

**Issue by aanriot** [saltstack-formulas/salt-formula#376]
Hello,

According to the SaltStack documentation on [publisher_acl](https://docs.saltstack.com/en/latest/ref/publisheracl.html), it is possible for each user to either list functions (it will apply to all minions), or minions and functions available on them, as subkeys. In the later case (see _user2_), we would have to handle 2 nested loops. For example:

```
publisher_acl:
    user1:
        - pkg.*
    user2:
        - prod.*:
            - pkg.*
```

For now, it seems that minion functions under minion names or patterns (see _user2_) are not supported by the formula, it will generate the following lines:

```
user2:
    - '{'prod.*': ['pkg.*']}'
```

instead of the working ones below:

```
user2:`
    - 'prod.*': ['pkg.*']
```

Any feeling on this? Do we have to support both cases in the formula?

Thanks a lot.
