### ISSUE TITLE
[salt-cloud] depended package pyVmomi is missing

### ISSUE THREAD

**Issue by grimsbane** [saltstack-formulas/salt-formula#380]
Hi,

seems after configure salt-cloud there depending packages missing (Debian jessie). 

salt-cloud --list-locations=all
[WARNING ] Missing dependency: 'pyVmomi'. The vmware driver requires 'pyVmomi' to be installed.
[WARNING ] The cloud driver, 'vmware', configured under the 'vmware-proj-prod' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'vmware' driver.
In rare cases, this could indicate the 'vmware.get_configured_provider()' function could not be found.
Removing 'vmware' from the available providers list
Error: There was an error listing locations: There are no cloud providers configured.

best regards
Nick

**Comment by grimsbane** [comment]
@nmadhok we could include this to salt-cloud-pip-packages, it is also possible to query for the condition driver= vmware.

```
salt-cloud-pip-packages:
  pip.installed:
    - pkgs:
      - apache-libcloud
      {%- if grains['os_family'] not in ['Debian', 'RedHat'] %}
      - crypto
      {%- endif %}
      - pycrypto
      - pyvmomi
    - require:
      - pkg: python-pip
```
