### ISSUE TITLE
Can't create ext_pillar config with nested lists

### ISSUE THREAD

**Issue by mrichar1** [saltstack-formulas/salt-formula#383]
I'm trying to add the following config via this formula:

```
ext_pillar:
  - saltclass:
    - path: /srv/salt/saltclass
```

However the logic in the formula doesn't seem to have a path that can output this style of config: https://github.com/saltstack-formulas/salt-formula/blob/master/salt/files/master.d/f_defaults.conf#L1180

It's probably possible to extend the logic to handle it, but given how horribly complex it already is, is there a reason not to just insert literal yaml in this kind of config, rather than trying to unpack yaml and rebuild it again?

Something like (untested):

```
{% if 'ext_pillar' in cfg_master %}
{%- do default_keys.append('ext_pillar') %}
ext_pillar:
  {{ cfg_master['ext_pillar'] | yaml }}
{% endif %}
```

**Comment by pcdummy** [comment]
For mongodb i use:

```yaml
salt:
  master:
    ext_pillar:
      - mongo: "{ collection: salt_pillar }"
```

Works for me (tm)

**Comment by aboe76** [comment]
@mrichar1 tried with the following config and it works:
```
salt:
  master:
    master_tops:
      saltclass: "{ path: /srv/saltclass }"
    ext_pillar:
      - saltclass: "[ path: /srv/saltclass ]"
```

**Comment by mrichar1** [comment]
Yep that's the solution I've gone with - will close this, thanks!

**Comment by aboe76** [comment]
This should be addressed if somebody else runs into this, they won't find this closed issue.

**Comment by adamcstephens** [comment]
For me, master_tops will actually take a dict, so the hack only seems to be necessary for ext_pillar:

```yaml
salt:
  master:                                                                                                
    ext_pillar:                                                                                          
      - saltclass: "[ path: /srv/saltclass ]"                                                                                                                                        
    master_tops:                                                                                         
      saltclass:                                                                                              
        path: /srv/saltclass   
```

```
❯ grep -A4 '^master_tops' /etc/salt/master.d/f_defaults.conf
master_tops:
  saltclass:
    path: /srv/saltclass
```
