### ISSUE TITLE
script_args global config not respected

### ISSUE THREAD

**Issue by ErisDS** [saltstack-formulas/salt-formula#420]
My cloud config looked like this:

```
cloud:
    script_args: stable 2017.7.8 
    provider: do
    minion:
      master: x.x.x.x

    providers:
      digital_ocean.conf:
        do:
          driver: digital_ocean
```

I was expecting that doing state.apply would result in the `script_args` line in `/etc/salt/cloud` would be updated.

Changing the config to 

```
```
cloud:
    provider: do
    minion:
      master: x.x.x.x

    providers:
      digital_ocean.conf:
        do:
          driver: digital_ocean
          script_args: stable 2017.7.8 # Hard-code salt-minion version
```

Correctly updates `/etc/salt/cloud.providers.d/digital_ocean.conf` and works.

However I'd expect that it would be possible to override the global value in `/etc/salt/cloud/`.

Caveat: i might be wrong about /etc/salt/cloud being the right place to honour this - in our system we have a `script_args` line in there, but it may have been hardcoded before we started using salt-formula.

The main point is that this config option is only respected within individual providers, and there is extremely limited documentation around that makes it clear this is how to configure script_args.

The fundamental point being needing to hardcode the minion to not fall behind the master.
