### ISSUE TITLE
salt-minion states fail on FreeBSD

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/salt-formula#431]
Py2 is hardcoded in osfamilymap
```
          ID: salt-minion
    Function: pkg.installed
        Name: py27-salt
      Result: False
     Comment: The following packages failed to install/update: py27-salt
     Started: 14:59:34.935576
    Duration: 8028.683 ms

Checking integrity... done (6 conflicting)
  - py27-salt-2016.11.2 [SaltStack] conflicts with py36-salt-2019.2.0_2 [installed] on /usr/local/etc/salt/master.sample
  - py27-salt-2019.2.0_2 [FreeBSD] conflicts with py36-salt-2019.2.0_2 [installed] on /usr/local/etc/salt/master.sample
  - py27-tornado-4.4.2 [SaltStack] conflicts with py27-tornado4-4.5.3 [installed] on /usr/local/lib/python2.7/site-packages/tornado/__init__.py
  - py27-setuptools27-32.1.0 [SaltStack] conflicts with py27-setuptools-41.1.0 [installed] on /usr/local/lib/python2.7/site-packages/easy-install.pth.dist
  - py27-setuptools27-32.1.0 [SaltStack] conflicts with py36-setuptools-41.1.0 [installed] on /usr/local/bin/easy_install
  - py27-msgpack-python-0.4.7 [SaltStack] conflicts with py27-msgpack-0.6.1 [installed] on /usr/local/lib/python2.7/site-packages/msgpack/__init__.py
Cannot solve problem using SAT solver, trying another plan
```

Versions
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Jun 11 2019, 01:16:36)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: US-ASCII
        machine: amd64
        release: 11.2-RELEASE
         system: FreeBSD
        version: Not Installed
```
