### ISSUE TITLE
slspath resolves to wrong path in salt-minion state

### ISSUE THREAD

**Issue by hkbakke** [saltstack-formulas/salt-formula#452]
When running salt.minion (on 3000+ds-1, Debian Buster) the salt-minion state fails on file.recurse because the source resolves to `salt://salt/minion/files/minion.d`.

```
salt-minion:

  file.recurse:
    - name: /etc/salt/minion.d
    - template: jinja
    - source: salt://salt/minion/files/minion.d
    - context:
        standalone: False
    - clean: True
    - exclude_pat: _*
```
That path does not exist. The correct path is `salt://salt/files/minion.d`. In the state `{{ slspath }}` is used, but if i change that to `{{ tplroot }}` it resolves to the correct path.

```
  file.recurse:
    - name: {{ salt_settings.config_path }}/minion.d
    {%- if salt_settings.minion_config_use_TOFS %}
    - template: ''
    - source: {{ files_switch(['minion.d'],
                              lookup='salt-minion'
                 )
              }}
    {%- else %}
    - template: jinja
    - source: salt://{{ slspath }}/files/minion.d   <---- change to {{ tplroot }}
    - context:
        standalone: False
```
