### ISSUE TITLE
Setting the salt.release version, doesn't trigger an update

### ISSUE THREAD

**Issue by xenadmin** [saltstack-formulas/salt-formula#454]
### Formula commit hash / release tag
latest

### Versions reports (master & minion)
Debian 9 amd64 for Master & Minion
Master: 2019.2.3
Minions: 2018.3.4

### Pillar / config used
```
salt:
  clean_config_d_dir: False
  minion_remove_config: False
  py_ver: 'py3'
  install_packages: True
  release: '2019.2'
  
  minion:
    master: salt.domain.de
```
---

### Describe the bug
Changing the pillar salt.release doesn't trigger an update & restart of the installed salt-minion.

### Steps to reproduce the bug
I change the release in my pillar from 2018.3 -> 2019.2 and save the file.
```
salt '*' saltutil.refresh_pillar -t 15
salt '*' state.apply
```
The saltstack.list file changes, but nothing else. 

### Expected behaviour
I would expect a "apt upgrade salt-minion -y" to trigger with a service restart at the end aka:
```
salt-minion:
  service.running:
    - watch:
      - pkg: {{ salt_settings.salt_minion }}
```

### Attempts to fix the bug
I have some experience in enhancing the zabbix-formula, but I'm cautions about the salt-formula.
I would suggest to add:
```
salt-minion:
  service.running:
    - watch:
      - pkg: {{ salt_settings.salt_minion }}
```
but I can only speak for Debian, and not for Mac and Win, so I'm asking if my question is valid. 

### Additional context
Trying to switch all my salt-minions from 2018.3 to 2019.2 in preparation for a Debian upgrade from 9 -> 10.

**Comment by myii** [comment]
@xenadmin Thanks for your report.  This is a tough one since upgrading minions can be tricky.  Let me get some other opinions from the other recent contributors.  @aboe76 @sticky-note, any thoughts on how to handle this?

**Comment by xenadmin** [comment]
I solved this already, and forgot to mention it here. I change my pillar to the following:

#### Pillar / config used
```
salt:
  clean_config_d_dir: False
  minion_remove_config: False
  py_ver: 'py3'
  install_packages: True
  release: '2019.2'
  version: '2019.2.3+ds-1'
  
  minion:
    master: salt.domain.de
```
Then I did a `salt '*' state.apply` **twice**, as the `cron.present:` states failed the first time, but not the second time. All minions are now on the latest 2019.2 version.
