### ISSUE TITLE
[FEATURE] When using external_auth, parameters starting with '^' should be placed first

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/salt-formula#455]
### Formula commit hash / release tag

current master

### Pillar / config used

If you want to use an external authentication, for example the file one https://docs.saltstack.com/en/latest/ref/auth/all/salt.auth.file.html, parameters are defined prefixing them with '^' and ACL are not.

```
salt:
  master:
    external_auth:
      file:
        ^filename: '/etc/salt/external_users.txt'
        ^hashtype: 'sha256'
        ^filetype: 'text'
        foo:
          '.*'
         bar:
          '.*.'
         baz:
          '.*.'
```

---

### Describe the bug

The code generating `/etc/salt/master.d/f_defaults.conf` takes all key/values and makes (nearly) no difference between parameters with '^' and ACL.

If you have a long list of ACL, parameters are lost in the middle of the ACL and not easily viewed in the config file.

The resulting config file can looks like:
```
external_auth:
  file:
    foo:
      - '.*'
    ^filename: '/etc/salt/external_users.txt'


    bar:
      - '.*'
    ^hashtype: 'sha256'
    baz:
      - '.*'
    ^filetype: 'text'
    foobar:
      - '.*'
```

### Expected behaviour

It may be interesting to differenciate how we manipulate auth parameters and ACL so we can write first the parameters and then the ACL.
