### ISSUE TITLE
[BUG] formulas state fails on Windows

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/salt-formula#485]
### Pillar / config used

---

### Describe the bug

I was running salt-formula/init.sls and there are many state failures on Windows which need investigation. 

Log attached.

**Comment by myii** [comment]
@noelmcloughlin That's a bit strange since we're successfully testing on Windows here:

* https://github.com/saltstack-formulas/salt-formula/runs/1028772636?check_suite_focus=true

Perhaps the `salt-minion` isn't installed properly.  You can compare with this:

https://github.com/saltstack-formulas/salt-formula/blob/2dcd0c80efbd0acd0ca832a3435b7f3dc21788eb/kitchen.github.yml#L13-L20

**Comment by noelmcloughlin** [comment]
The suite runs `salt.minion` which probably works okay. 
I'm running `salt.init` which calls `salt.formulas` and that state is giving failures.

**Comment by noelmcloughlin** [comment]
Looks like  `parallel: True` does not work on Windows!
```
foo_app:
  git.latest:
    - name: https://github.com/saltstack-formulas/salt-formula.git
    - target: /tmp/bob
    - parallel: False  # True causes failed state
```
